### PR TITLE
Thread Credential Sharing

### PR DESCRIPTION
**Pull request by rochaferraz**
PR adds Google Play Services' **Thread Credential Sharing** functionality to Google Home Sample App for Matter under **Configuration Wheel** > **Developer utilities** > **Thread network**

### CODE REVIEW

**Comment by zimmyxyz** [comment]
Gave this PR a try and it's causing a crash on app startup:
```
---------------------------- PROCESS STARTED (12118) for package com.google.homesampleapp.default ----------------------------
  E  FATAL EXCEPTION: main
     Process: com.google.homesampleapp.default, PID: 12118
     java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/~~RQZzs8mvD2szhieOVDstdA==/com.google.homesampleapp.default-2JHc7oT56w5u_cMlHINRDQ==/base.apk!/lib/arm64-v8a/libCHIPController.so" has bad ELF magic: 76657273
     	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
     	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
     	at java.lang.System.loadLibrary(System.java:1661)
     	at chip.devicecontroller.ChipDeviceController.<clinit>(ChipDeviceController.java:882)
     	at chip.devicecontroller.ChipDeviceController.loadJni(ChipDeviceController.java:46)
     	at com.google.homesampleapp.chip.ChipClient$chipDeviceController$2.invoke(ChipClient.kt:51)
     	at com.google.homesampleapp.chip.ChipClient$chipDeviceController$2.invoke(ChipClient.kt:50)
     	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
     	at com.google.homesampleapp.chip.ChipClient.getChipDeviceController(ChipClient.kt:50)
     	at com.google.homesampleapp.screens.home.HomeFragment.setDeviceAttestationDelegate(HomeFragment.kt:452)
     	at com.google.homesampleapp.screens.home.HomeFragment.onCreate(HomeFragment.kt:154)
     	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3090)
     	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
     	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
     	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
     	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1823)
     	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
     	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2985)
     	at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2884)
     	at androidx.fragment.app.Fragment.onCreate(Fragment.java:1967)
     	at androidx.navigation.fragment.NavHostFragment.onCreate(NavHostFragment.kt:169)
     	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3090)
     	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
     	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
     	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
     	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1823)
     	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1729)
     	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:323)
     	at androidx.fragment.app.FragmentContainerView.<init>(FragmentContainerView.kt:158)
     	at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:53)
     	at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:136)
     	at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:248)
     	at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:227)
     	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1073)
     	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1001)
     	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
     	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
     	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
     	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
     	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
     	at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
     	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:710)
     	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
     	at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:303)
     	at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:284)
  E  	at com.google.homesampleapp.MainActivity.onCreate(MainActivity.kt:41)
     	at android.app.Activity.performCreate(Activity.java:8341)
     	at android.app.Activity.performCreate(Activity.java:8320)
     	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
     	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3622)
     	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3778)
     	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
     	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
     	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
     	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2303)
     	at android.os.Handler.dispatchMessage(Handler.java:106)
     	at android.os.Looper.loopOnce(Looper.java:201)
     	at android.os.Looper.loop(Looper.java:288)
     	at android.app.ActivityThread.main(ActivityThread.java:7884)
     	at java.lang.reflect.Method.invoke(Native Method)
     	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by rochaferraz** [comment]
Interesting. Thanks for trying it out! It works fine in my local build and this PR shouldn't interfere with how the Matter library is loaded. Can you revert to `main` and confirm the issue doesn't also occur there?

@pierredelisle

**Comment by rochaferraz** [comment]
Maybe changing branches triggers `git-lfs` to change the library file?

**Comment by pierredelisle** [comment]
@zimmyxyz Yeah, there's an issue with the PR. New one coming up soon.

**Pull request closed without merging**
